// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnkSQMn-2bleWAlEEBAvkV3gryvm99o9g',
    appId: '1:1085716868502:android:0bae3fe081fc213b0681b7',
    messagingSenderId: '1085716868502',
    projectId: 'cogniloop-72b3b',
    storageBucket: 'cogniloop-72b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQu0ZRYyqnR_KajBshQq5PMKXvvxaWBck',
    appId: '1:1085716868502:ios:00255ec7c159195f0681b7',
    messagingSenderId: '1085716868502',
    projectId: 'cogniloop-72b3b',
    storageBucket: 'cogniloop-72b3b.firebasestorage.app',
    androidClientId: '1085716868502-6g6nflrnh30dn0lbigvred81tbc1pure.apps.googleusercontent.com',
    iosClientId: '1085716868502-ugd1dgj2pjatdahos036mgep2q79sfim.apps.googleusercontent.com',
    iosBundleId: 'com.example.cogniLoop',
  );
}
